name: Publish to PyPI and Test PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        index-url: ['https://test.pypi.org/legacy/', 'https://upload.pypi.org/legacy/']

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full repository is checked out

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build the package
        run: |
          python -m build  # Automatically detects `pyproject.toml`
          
  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      pypi: ''  # Specify the PyPI environment
    permissions:
      id-token: write  # Required for Trusted Publishing
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages_dir: ./dist